### ISSUE TITLE
请问能否加入新的插件

### ISSUE THREAD

**Issue by PBnicad** [nonebotjs/koishi-plugin-nonebot#15]
请问能否加入以下插件？
https://github.com/paul-sama/splatoon3-bot

**Comment by CyanChanges** [comment]
你确定你这是一个新插件

**Comment by CyanChanges** [comment]
<img width="431" alt="image" src="https://github.com/nonebotjs/koishi-plugin-nonebot/assets/68551684/23896f4b-d440-4ba0-89e6-bc2d95eedcb7">  

这个 Bot 依赖了 SQLAlchemy
<img width="357" alt="image" src="https://github.com/nonebotjs/koishi-plugin-nonebot/assets/68551684/2cfb476d-fb9c-4b7f-a1ba-de493529095d">  

还有 requests

**Comment by PBnicad** [comment]
> 你确定你这是一个新插件

是的，商店里有个原生的只能查地图，这个可以查战绩

**Comment by PBnicad** [comment]
> <img alt="image" width="431" src="https://user-images.githubusercontent.com/68551684/245139637-23896f4b-d440-4ba0-89e6-bc2d95eedcb7.png"> 这里面依赖了一个SQLAlchemy

意思是不能移植吗

**Comment by PBnicad** [comment]
> <img alt="image" width="431" src="https://user-images.githubusercontent.com/68551684/245139637-23896f4b-d440-4ba0-89e6-bc2d95eedcb7.png">
> 这个 Bot 依赖了 SQLAlchemy <img alt="image" width="357" src="https://user-images.githubusercontent.com/68551684/245140990-2cfb476d-fb9c-4b7f-a1ba-de493529095d.png">
> 
> 还有 requests

是pyodide不支持SQLAlchemy吗

**Comment by PBnicad** [comment]
> <img alt="image" width="431" src="https://user-images.githubusercontent.com/68551684/245139637-23896f4b-d440-4ba0-89e6-bc2d95eedcb7.png">
> 这个 Bot 依赖了 SQLAlchemy <img alt="image" width="357" src="https://user-images.githubusercontent.com/68551684/245140990-2cfb476d-fb9c-4b7f-a1ba-de493529095d.png">
> 
> 还有 requests

![sql](https://github.com/nonebotjs/koishi-plugin-nonebot/assets/36125594/2d101056-dd9a-4f35-8406-b126d887600c)
我查文档说是添加了这个包啊

**Comment by shigma** [comment]
我记得 requests 不太行吧？（如果请求是同步的就做不了）

建议换成 httpx 或者 aiohttp（

**Comment by PBnicad** [comment]
> 我记得 requests 不太行吧？（如果请求是同步的就做不了）
> 
> 建议换成 httpx 或者 aiohttp（

好的
